server:
  port: 7900
  
spring:
  application:
    name: order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zh?useSSL=false
    username: root
    password: root
            
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.zh.entiy
  mapperLocations: classpath:dao/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.zh.dao: INFO